--- #my loops playbooks
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: installing  multiple packages
            user: name='{{item}}' state=present
            with_items:
                    - xyz
                    - abc
                 
                    
                    
                    

