--- #task section
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: installing httpd in webservers group
            yum: name=httpd state=installed
            ignore_errors: yes
